name: 'Generate Hyperscale Matrix'
description: 'Generate a dynamically scaled matrix of runners for running Playwright tests in parallel'
inputs:
  scope:
    description: 'Playwright scope for selecting the tests to run (Runs all tests if empty)'
    required: false
    default: ''
outputs:
  matrix:
    description: 'The GitHub runner matrix'
runs:
  using: "node20"
  main: "dist/index.js"