name: Playwright-Test-Sharded
on:
  workflow_dispatch:
    inputs:
      scope:
        description: 'Playwright scope for selecting the tests to run (Runs all tests if empty)'
        required: false
        default: ''
      index:
        description: 'Index of the shard to run'
        required: true
      total:
        description: 'Total number of shards'
        required: true
jobs:
    test:
        runs-on: ubuntu-latest
        defaults:
           run:
             working-directory: './sample-projects/sample-playwright-hyperscaled'
        steps:
          - name: "Checkout code"
            uses: actions/checkout@v4

          - name: Setup Node.js
            uses: actions/setup-node@v4
            with:
              node-version: "20"

          - name: Install dependencies
            run: npm ci

          - name: Run tests sharded
            id: run
            uses: ./playwright-test-sharded
            with:
              scope: ${{ github.event.inputs.scope }}
              index: ${{ github.event.inputs.index }}
              total: ${{ github.event.inputs.total }}

          - name: Upload report
            uses: actions/upload-artifact@v4
            if: ${{ !cancelled() }}
            with:
              name: playwright-report
              path: sample-projects/sample-playwright-hyperscaled/playwright-report/
              retention-days: 30
